src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductoRepository::class)]
class Producto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $descripcion = null;

    #[ORM\Column(length: 255)]
    private ?string $codigo = null;

    #[ORM\ManyToOne(inversedBy: 'productos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?CategoriaProducto $categoria = null;

    #[ORM\Column]
    private ?float $precio_actual = null;

    #[ORM\Column(nullable: true)]
    private ?float $stock_actual = null;

    /**
     * @var Collection<int, PrecioHistorico>
     */
    #[ORM\OneToMany(targetEntity: PrecioHistorico::class, mappedBy: 'producto')]
    private Collection $precioHistoricos;

    /**
     * @var Collection<int, StockMovimiento>
     */
    #[ORM\OneToMany(targetEntity: StockMovimiento::class, mappedBy: 'producto')]
    private Collection $stockMovimientos;

    /**
     * @var Collection<int, VentaDetalle>
     */
    #[ORM\OneToMany(mappedBy: 'producto', targetEntity: VentaDetalle::class, cascade: ['persist', 'remove'])]
    private Collection $ventaDetalles;

    public function __construct()
    {
        $this->precioHistoricos = new ArrayCollection();
        $this->stockMovimientos = new ArrayCollection();
        $this->ventaDetalles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    public function setCodigo(string $codigo): static
    {
        $this->codigo = $codigo;

        return $this;
    }

    public function getCategoria(): ?CategoriaProducto
    {
        return $this->categoria;
    }

    public function setCategoria(?CategoriaProducto $categoria): static
    {
        $this->categoria = $categoria;

        return $this;
    }

    public function getPrecioActual(): ?float
    {
        return $this->precio_actual;
    }

    public function setPrecioActual(float $precio_actual): static
    {
        $this->precio_actual = $precio_actual;

        return $this;
    }

    public function getStockActual(): ?float
    {
        return $this->stock_actual;
    }

    public function setStockActual(?float $stock_actual): static
    {
        $this->stock_actual = $stock_actual;

        return $this;
    }

    /**
     * @return Collection<int, PrecioHistorico>
     */
    public function getPrecioHistoricos(): Collection
    {
        return $this->precioHistoricos;
    }

    public function addPrecioHistorico(PrecioHistorico $precioHistorico): static
    {
        if (!$this->precioHistoricos->contains($precioHistorico)) {
            $this->precioHistoricos->add($precioHistorico);
            $precioHistorico->setProducto($this);
        }

        return $this;
    }

    public function removePrecioHistorico(PrecioHistorico $precioHistorico): static
    {
        if ($this->precioHistoricos->removeElement($precioHistorico)) {
            // set the owning side to null (unless already changed)
            if ($precioHistorico->getProducto() === $this) {
                $precioHistorico->setProducto(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, StockMovimiento>
     */
    public function getStockMovimientos(): Collection
    {
        return $this->stockMovimientos;
    }

    public function addStockMovimiento(StockMovimiento $stockMovimiento): static
    {
        if (!$this->stockMovimientos->contains($stockMovimiento)) {
            $this->stockMovimientos->add($stockMovimiento);
            $stockMovimiento->setProducto($this);
        }

        return $this;
    }

    public function removeStockMovimiento(StockMovimiento $stockMovimiento): static
    {
        if ($this->stockMovimientos->removeElement($stockMovimiento)) {
            // set the owning side to null (unless already changed)
            if ($stockMovimiento->getProducto() === $this) {
                $stockMovimiento->setProducto(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, VentaDetalle>
     */
    public function getVentaDetalles(): Collection
    {
        return $this->ventaDetalles;
    }

    public function addVentaDetalle(VentaDetalle $ventaDetalle): static
    {
        if (!$this->ventaDetalles->contains($ventaDetalle)) {
            $this->ventaDetalles->add($ventaDetalle);
            $ventaDetalle->setProducto($this);
        }

        return $this;
    }

    public function removeVentaDetalle(VentaDetalle $ventaDetalle): static
    {
        if ($this->ventaDetalles->removeElement($ventaDetalle)) {
            if ($ventaDetalle->getProducto() === $this) {
                $ventaDetalle->setProducto(null);
            }
        }

        return $this;
    }
}

src/Form/ProductoType.php
<?php

namespace App\Form;

use App\Entity\CategoriaProducto;
use App\Entity\Producto;
use App\Entity\Sucursal;
use Dom\Entity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class ProductoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre', null, [
                'label' => 'Nombre del Producto',
                'required' => true
            ])
            ->add('descripcion', null, [
                'label' => 'Descripción del Producto',
                'required' => false
            ])
            ->add('codigo', null, [
                'label' => 'Código del Producto',
                'required' => true
            ])
            ->add('precio_actual', null, [
                'label' => 'Precio del Producto',
                'required' => true
            ])
            ->add('categoria', EntityType::class, [
                'class' => CategoriaProducto::class,
                'choice_label' => 'nombre',
                'label' => 'Categoría',
                'placeholder' => 'Seleccione una categoría',
                'required' => true,
            ])
            ->add('nueva_categoria', TextType::class, [
                'label' => 'Nueva Categoría',
                'required' => false,
                'mapped' => false,
                'label' => false,
                'attr' => ['style' => 'display:none;'],
            ])
            ->add('sucursal', EntityType::class, [
                'class' => Sucursal::class,
                'choice_label' => 'nombre',
                'placeholder' => 'Seleccione una sucursal',
                'required' => false,
                'mapped' => false,
                'label' => false, 
                'attr' => ['style' => 'display:none;'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Producto::class,
            'categorias' => [],
            'sucursales' => [],
        ]);
    }
}

src/Controller/ProductoController.php
<?php

namespace App\Controller;

use App\Entity\CategoriaProducto;
use App\Entity\PrecioHistorico;
use App\Entity\Producto;
use App\Form\ProductoType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/producto')]
final class ProductoController extends AbstractController
{
    #[Route(name: 'app_producto_index')]
    public function index(): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $productos = [];
        $negocios = $this->getUser()->getNegocios();
        foreach ($negocios as $negocio) {
            $sucursales = $negocio->getSucursales();
            foreach ($sucursales as $sucursal) {
                $categorias = $sucursal->getCategoriaProductos();
                foreach ($categorias as $categoria) {
                    $productos = array_merge($productos, $categoria->getProductos()->toArray());
                }
            }
        }
        return $this->render('producto/index.html.twig', [
            'productos' => $productos
        ]);
    }

    #[Route('/new', name: 'app_producto_new')]
    public function create(
        EntityManagerInterface $entityManager,
        Request $request
    ): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }

        $categorias = [];
        foreach ($entityManager->getRepository(CategoriaProducto::class)->findAll() as $cat) {
            $categorias[$cat->getNombre()] = $cat->getId();
        }

        $sucursales = [];
        foreach ($this->getUser()->getNegocios() as $negocio) {
            if (count($negocio->getSucursales()) > 1) {
                foreach ($negocio->getSucursales() as $sucursal) {
                    $sucursales[$sucursal->getNombre()] = $sucursal->getId();
                }
            }else {
                $sucursal = $negocio->getSucursales()[0];
            }
        }

        $productoForm = $this->createForm(ProductoType::class, null, [
            'categorias' => $categorias,
            'sucursales' => $sucursales,
        ]);

        $productoForm->handleRequest($request);

        if ($productoForm->isSubmitted() && $productoForm->isValid()) {
            
            $producto = $productoForm->getData();

            if ($producto->getCategoria()->getId() === 1) {
                $nombreNuevaCategoria = $productoForm->get('nueva_categoria')->getData();
                if ($sucursales != []) {
                    $sucursal = $productoForm->get('sucursal')->getData();
                }
                $categoria = new CategoriaProducto();
                $categoria->setNombre($nombreNuevaCategoria);
                $categoria->setSucursal($sucursal);
                $entityManager->persist($categoria);
                $entityManager->flush();
                $producto->setCategoria($categoria);
            }

            $historialPrecio = new PrecioHistorico();
            $historialPrecio->setProducto($producto);
            $historialPrecio->setPrecio($producto->getPrecioActual());
            $historialPrecio->setFechaDesde(new \DateTimeImmutable('now', new \DateTimeZone('America/Argentina/Buenos_Aires')));
            $entityManager->persist($historialPrecio);

            $entityManager->persist($producto);
            $entityManager->flush();

            $this->addFlash('success', 'Producto creado con éxito.');
            return $this->redirectToRoute('app_producto_index');
        }

        return $this->render('producto/new.html.twig', [
            'productoForm' => $productoForm,
        ]);
    }

    #[Route('/{id}', name: 'app_producto_show', methods: ['GET'])]
    public function show(Producto $producto): Response
    {
        return $this->render('producto/show.html.twig', [
            'producto' => $producto,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_producto_edit')]
    public function edit(
        Request $request,
        Producto $producto,
        EntityManagerInterface $entityManager,
    ): Response
    {
        $categorias = [];
        foreach ($entityManager->getRepository(CategoriaProducto::class)->findAll() as $cat) {
            $categorias[$cat->getNombre()] = $cat->getId();
        }

        $sucursales = [];
        foreach ($this->getUser()->getNegocios() as $negocio) {
            if (count($negocio->getSucursales()) > 1) {
                foreach ($negocio->getSucursales() as $sucursal) {
                    $sucursales[$sucursal->getNombre()] = $sucursal->getId();
                }
            }else {
                $sucursal = $negocio->getSucursales()[0];
            }
        }

        $productoForm = $this->createForm(ProductoType::class, $producto, [
            'categorias' => $categorias,
            'sucursales' => $sucursales,
        ]);

        $productoForm->handleRequest($request);

        if ($productoForm->isSubmitted() && $productoForm->isValid()) {
            if ($producto->getCategoria()->getId() === 1) {
                $nombreNuevaCategoria = $productoForm->get('nueva_categoria')->getData();
                if ($sucursales != []) {
                    $sucursal = $productoForm->get('sucursal')->getData();
                }
                $categoria = new CategoriaProducto();
                $categoria->setNombre($nombreNuevaCategoria);
                $categoria->setSucursal($sucursal);
                $entityManager->persist($categoria);
                $entityManager->flush();
                $producto->setCategoria($categoria);
            }

            $historialPrecioLast = $producto->getPrecioHistoricos()->last();
            if ($historialPrecioLast->getPrecio() != $producto->getPrecioActual()) {
                $historialPrecioLast->setFechaHasta(new \DateTimeImmutable('now', new \DateTimeZone('America/Argentina/Buenos_Aires')));
                $entityManager->persist($historialPrecioLast);    

                $historialPrecioNew = new PrecioHistorico();
                $historialPrecioNew->setProducto($producto);
                $historialPrecioNew->setPrecio($producto->getPrecioActual());
                $historialPrecioNew->setFechaDesde(new \DateTimeImmutable('now', new \DateTimeZone('America/Argentina/Buenos_Aires')));
                $entityManager->persist($historialPrecioNew);
                $entityManager->persist($producto);
            }

            $entityManager->flush();
            $this->addFlash('success', 'Producto actualizado con éxito.');
            return $this->redirectToRoute('app_producto_index');
        }
        
        return $this->render('producto/edit.html.twig', [
            'productoForm' => $productoForm,
            'producto' => $producto,
        ]); 
    }

    #[Route('/{id}/delete', name: 'app_producto_delete')]
    public function delete(
        EntityManagerInterface $entityManager,
        int $id
    ): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }

        $producto = $entityManager->getRepository('App\Entity\Producto')->find($id);

        if (!$producto) {
            $this->addFlash('error', 'Producto no encontrado.');
            return $this->redirectToRoute('app_producto_index');
        }

        $historialPrecio = $producto->getPrecioHistoricos();
        foreach ($historialPrecio as $hp) {
            $entityManager->remove($hp);
        }

        $entityManager->remove($producto);
        $entityManager->flush();

        $this->addFlash('success', 'Producto eliminado con éxito.');
        return $this->redirectToRoute('app_producto_index');
    }
}

templates/producto/_delete_form.html.twig
<form method="post" action="{{ path('app_producto_delete', {'id': producto.id}) }}" style="display:inline-block;" onsubmit="return confirm('¿Está seguro de que desea eliminar este producto?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ producto.id) }}">
    <button class="btn btn-danger btn-sm">Eliminar</button>
</form>

templates/producto/_form.html.twig
{{ form_errors(productoForm) }}

{{ form_start(productoForm, { 'attr': { 'class': 'needs-validation text-start', 'novalidate': true } }) }}
    <div class="row">
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.nombre, 'Nombre', { 'label_attr': { 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.nombre, { 
                'attr': { 
                'class': 'form-control',
                'required': true
            }
            }) }}
            <div class="invalid-feedback">
                Por favor ingrese un nombre.
            </div>
            {{ form_errors(productoForm.nombre) }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.descripcion, 'Descripción', { 'label_attr': { 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.descripcion, { 
                'attr': { 
                'class': 'form-control',
                'required': false
            }
            }) }}
            <div class="invalid-feedback">
                Por favor ingrese un código.
            </div>
            {{ form_errors(productoForm.descripcion) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.codigo, 'Código', { 'label_attr': { 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.codigo, { 
                'attr': { 
                'class': 'form-control',
                'required': true
            }
            }) }}
            <div class="invalid-feedback">
                Por favor ingrese un código.
            </div>
            {{ form_errors(productoForm.codigo) }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.categoria, 'Categoría', { 'label_attr': { 'id': 'producto_categoria_label', 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.categoria, { 'attr': { 'class': 'form-select', 'id': 'producto_categoria', 'required': true } }) }}
            <div class="invalid-feedback">
                Por favor seleccione una categoría.
            </div>
            {{ form_errors(productoForm.categoria) }}
            <div id="nueva-categoria-div" style="display:none;">
                {{ form_label(productoForm.nueva_categoria, 'Nueva Categoría', { 'label_attr': { 'class': 'form-label' } }) }}
                {{ form_widget(productoForm.nueva_categoria, { 'attr': { 'id': 'nueva-categoria', 'class': 'form-control' } }) }}
                {{ form_errors(productoForm.nueva_categoria) }}
                <div class="invalid-feedback">
                    Por favor ingrese una nueva categoría.
                </div>
            </div>
        </div>
    </div>
    {% if productoForm.sucursal|length > 1 %}
    <div class="row">
        <div class="col-md-6 mb-3"></div>
        <div class="col-md-6 mb-3">
            <div id="nueva-categoria-sucursal-div" style="display:none;">
                {{ form_label(productoForm.sucursal, 'Sucursal', { 'label_attr': { 'class': 'form-label' } }) }}
                {{ form_widget(productoForm.sucursal, { 'attr': { 'class': 'form-select', 'id': 'producto_sucursal' } }) }}
                <div class="invalid-feedback">
                    Por favor seleccione una sucursal.
                </div>
                {{ form_errors(productoForm.sucursal) }}
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.precio_actual, 'Precio', { 'label_attr': { 'class': 'form-label' } }) }}
            
            {% set precio_raw = productoForm.precio_actual.vars.value|default('') %}
            {% if precio_raw != '' %}
                {% set precio_num = (precio_raw|replace({',': '.'})) %}
                {% set precio_val_formatted = precio_num|number_format(2, '.', '') %}
            {% else %}
                {% set precio_val_formatted = '' %}
            {% endif %}

            {{ form_widget(productoForm.precio_actual, { 
                'type': 'number',
                'attr': { 
                'step': '0.01',
                'class': 'form-control',
                'min': '0',
                'required': true,
                'value': precio_val_formatted
            }
            }) }}
            <div class="invalid-feedback">
                Por favor ingrese un precio.
            </div>
            {{ form_errors(productoForm.precio_actual) }}
        </div>
    </div>
    <button class="btn btn-primary btn-sm">{{ button_label|default('Crear') }}</button>
{{ form_end(productoForm) }}

<script>
    document.getElementById('producto_categoria').addEventListener('change', function() {
        var nuevaCatDiv = document.getElementById('nueva-categoria-div');
        var nuevaCatSucDiv = document.getElementById('nueva-categoria-sucursal-div');
        var inputNuevaCat = document.getElementById('nueva-categoria');
        var selectCat = document.getElementById('producto_categoria');
        var inputNuevaCat = nuevaCatDiv.querySelector('input');
        var labelCat = document.getElementById('producto_categoria_label');
        
        if (nuevaCatSucDiv) {
            var inputNuevaCatSuc = nuevaCatSucDiv.querySelector('input');
            var selectSucursal = document.getElementById('producto_sucursal');
        }

        if (this.value === '1') {
            nuevaCatDiv.style.display = 'block';
            inputNuevaCat.style.display = 'block';
            inputNuevaCat.required = true;
            if (nuevaCatSucDiv) {
                inputNuevaCatSuc.required = true;
                nuevaCatSucDiv.style.display = 'block';
                selectSucursal.style.display = 'block';
                selectSucursal.required = true;
            }
            labelCat.style.display = 'none';
            selectCat.style.display = 'none';
            selectCat.required = false;
        }
    });

    (function () {
        'use strict'

        var forms = document.querySelectorAll('.needs-validation')

        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>

templates/producto/create.html.twig
{% extends 'base.html.twig' %}



{% block body %}
<h1>{% block title %}Crear Producto{% endblock %}</h1>

{{ form_errors(productoForm) }}

{{ form_start(productoForm, { 'attr': { 'class': 'needs-validation text-start', 'novalidate': true } }) }}
    <div class="row">
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.nombre, 'Nombre', { 'label_attr': { 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.nombre, { 
                'attr': { 
                'class': 'form-control',
                'required': true
            }
            }) }}
            <div class="invalid-feedback">
                Por favor ingrese un nombre.
            </div>
            {{ form_errors(productoForm.nombre) }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.descripcion, 'Descripción', { 'label_attr': { 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.descripcion, { 
                'attr': { 
                'class': 'form-control',
                'required': false
            }
            }) }}
            <div class="invalid-feedback">
                Por favor ingrese un código.
            </div>
            {{ form_errors(productoForm.descripcion) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.codigo, 'Código', { 'label_attr': { 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.codigo, { 
                'attr': { 
                'class': 'form-control',
                'required': true
            }
            }) }}
            <div class="invalid-feedback">
                Por favor ingrese un código.
            </div>
            {{ form_errors(productoForm.codigo) }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form_label(productoForm.categoria, 'Categoría', { 'label_attr': { 'id': 'producto_categoria_label', 'class': 'form-label' } }) }}
            {{ form_widget(productoForm.categoria, { 'attr': { 'class': 'form-select', 'id': 'producto_categoria', 'required': true } }) }}
            <div class="invalid-feedback">
                Por favor seleccione una categoría.
            </div>
            {{ form_errors(productoForm.categoria) }}
            <div id="nueva-categoria-div" style="display:none;">
                {{ form_label(productoForm.nueva_categoria, 'Nueva Categoría', { 'label_attr': { 'class': 'form-label' } }) }}
                {{ form_widget(productoForm.nueva_categoria, { 'attr': { 'id': 'nueva-categoria', 'class': 'form-control' } }) }}
                {{ form_errors(productoForm.nueva_categoria) }}
                <div class="invalid-feedback">
                    Por favor ingrese una nueva categoría.
                </div>
            </div>
        </div>
    </div>
    {% if productoForm.sucursal|length > 1 %}
    <div class="row">
        <div class="col-md-6 mb-3"></div>
        <div class="col-md-6 mb-3">
            <div id="nueva-categoria-sucursal-div" style="display:none;">
                {{ form_label(productoForm.sucursal, 'Sucursal', { 'label_attr': { 'class': 'form-label' } }) }}
                {{ form_widget(productoForm.sucursal, { 'attr': { 'class': 'form-select', 'id': 'producto_sucursal' } }) }}
                <div class="invalid-feedback">
                    Por favor seleccione una sucursal.
                </div>
                {{ form_errors(productoForm.sucursal) }}
            </div>
        </div>
    </div>
    {% endif %}
    <button class="btn btn-primary" type="submit">Crear Producto</button>
{{ form_end(productoForm) }}

<script>
    document.getElementById('producto_categoria').addEventListener('change', function() {
        var nuevaCatDiv = document.getElementById('nueva-categoria-div');
        var nuevaCatSucDiv = document.getElementById('nueva-categoria-sucursal-div');
        var inputNuevaCat = document.getElementById('nueva-categoria');
        var selectCat = document.getElementById('producto_categoria');
        var inputNuevaCat = nuevaCatDiv.querySelector('input');
        var labelCat = document.getElementById('producto_categoria_label');
        
        if (nuevaCatSucDiv) {
            var inputNuevaCatSuc = nuevaCatSucDiv.querySelector('input');
            var selectSucursal = document.getElementById('producto_sucursal');
        }

        if (this.value === '1') {
            nuevaCatDiv.style.display = 'block';
            inputNuevaCat.style.display = 'block';
            inputNuevaCat.required = true;
            if (nuevaCatSucDiv) {
                inputNuevaCatSuc.required = true;
                nuevaCatSucDiv.style.display = 'block';
                selectSucursal.style.display = 'block';
                selectSucursal.required = true;
            }
            labelCat.style.display = 'none';
            selectCat.style.display = 'none';
            selectCat.required = false;
        }
    });

    (function () {
        'use strict'

        var forms = document.querySelectorAll('.needs-validation')

        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>

{% endblock %}

templates/producto/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>{% block title %}Editar Producto{% endblock %}</h1>

    {{ include('producto/_form.html.twig', {'button_label': 'Actualizar', }) }}

    <a href="{{ path('app_producto_index') }}" class="btn btn-secondary btn-sm">Volver</a>

    {{ include('producto/_delete_form.html.twig') }}
{% endblock %}

templates/producto/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>{% block title %}Crear Producto{% endblock %}</h1>

{{ include('producto/_form.html.twig') }}

<a href="{{ path('app_producto_index') }}" class="btn btn-secondary btn-sm">Volver</a>

{% endblock %}

templates/producto/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>{% block title %}Producto{% endblock %}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ producto.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ producto.nombre }}</td>
            </tr>
            <tr>
                <th>Descripción</th>
                <td>{{ producto.descripcion }}</td>
            </tr>
            <tr>
                <th>Código</th>
                <td>{{ producto.codigo }}</td>
            </tr>
            <tr>
                <th>Categoría</th>
                <td>{{ producto.categoria.nombre }}</td>
            </tr>
            <tr>
                <th>Precio Actual</th>
                <td>$ {{ producto.precioActual }}</td>
            </tr>
        </tbody>
    </table>
    <p>Historial de precios</p>
    <table class="table">
        <thead>
            <tr>
                <th>Fecha Desde</th>
                <th>Fecha Hasta</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            {% for precio in producto.precioHistoricos %}
                <tr>
                    <td>{{ precio.getFechaDesde|date('d/m/Y H:i:s') }}</td>
                    <td>{% if precio.getFechaHasta %}{{ precio.getFechaHasta|date('d/m/Y H:i:s') }}{% else %}Actual{% endif %}</td>
                    <td>$ {{ precio.precio }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_producto_index') }}" class="btn btn-secondary btn-sm">Volver</a>

    <a href="{{ path('app_producto_edit', {'id': producto.id}) }}" class="btn btn-primary btn-sm">Editar</a>

    {{ include('producto/_delete_form.html.twig') }}
{% endblock %}